wl_states_n4k3g4_w = [
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                2,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                -1,
                3,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                2,
                2
            ],
            [
                -1,
                1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                2,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                0,
                2
            ],
            [
                1,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                1,
                3
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                1,
                2
            ],
            [
                -1,
                -1,
                0
            ],
            [
                1,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                1,
                1
            ],
            [
                -1,
                0,
                1
            ],
            [
                0,
                1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                -1,
                1,
                1
            ],
            [
                -1,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                -1,
                0,
                1
            ],
            [
                1,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                2,
                3
            ],
            [
                -1,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                1,
                3
            ],
            [
                2,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                -1,
                1,
                2
            ],
            [
                1,
                1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                0,
                1,
                2
            ],
            [
                0,
                1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                0,
                1
            ],
            [
                0,
                1,
                1
            ],
            [
                0,
                1,
                1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                0,
                0,
                1
            ],
            [
                0,
                0,
                1
            ],
            [
                0,
                0,
                1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                0
            ],
            [
                0,
                0,
                1
            ],
            [
                0,
                0,
                1
            ],
            [
                0,
                0,
                1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                0,
                0
            ],
            [
                0,
                0,
                1
            ],
            [
                0,
                0,
                1
            ],
            [
                0,
                0,
                1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    }
];
