wl_states_n6k3g7_w = [
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                6,
                6
            ],
            [
                -1,
                -1,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                6
            ],
            [
                -1,
                5,
                5
            ],
            [
                -1,
                -1,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                3,
                3
            ],
            [
                3,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                4,
                4
            ],
            [
                3,
                4,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                3,
                3
            ],
            [
                3,
                3,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                4,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                5,
                5,
                5
            ],
            [
                -1,
                -1,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                4,
                4,
                5
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                5,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                5,
                6
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                5,
                5
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                6,
                6,
                6
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                5,
                5,
                6
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                4,
                5,
                5
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                3,
                5
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                5,
                5,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                5
            ],
            [
                -1,
                -1,
                3
            ],
            [
                5,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                2,
                5
            ],
            [
                -1,
                3,
                4
            ],
            [
                4,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                6
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                -1,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                -1,
                2
            ],
            [
                -1,
                3,
                4
            ],
            [
                4,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                2,
                4
            ],
            [
                -1,
                2,
                3
            ],
            [
                3,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                4,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                3,
                3
            ],
            [
                -1,
                -1,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                4,
                4,
                6
            ],
            [
                -1,
                -1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                6
            ],
            [
                5,
                5,
                5
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                4,
                4,
                5
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ],
            [
                3,
                4,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                3,
                3
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                5
            ],
            [
                4,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                3,
                3,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                5,
                5
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                3,
                4
            ],
            [
                4,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                3,
                4,
                5
            ],
            [
                3,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                2,
                4,
                4
            ],
            [
                2,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                5
            ],
            [
                4,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                4,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                3,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                2,
                4
            ],
            [
                2,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                3,
                5
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                4,
                4,
                5
            ],
            [
                -1,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                2,
                4
            ],
            [
                3,
                4,
                4
            ],
            [
                -1,
                2,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                3,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                4,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                4,
                4,
                6
            ],
            [
                -1,
                3,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                3,
                4,
                5
            ],
            [
                -1,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                -1,
                2
            ],
            [
                3,
                4,
                4
            ],
            [
                -1,
                2,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                3
            ],
            [
                -1,
                2,
                3
            ],
            [
                2,
                3,
                4
            ],
            [
                -1,
                2,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                2
            ],
            [
                3,
                3,
                3
            ],
            [
                3,
                3,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                4,
                4,
                5
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                3,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                3,
                4,
                4
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                3,
                4,
                4
            ],
            [
                3,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                3,
                3,
                3
            ],
            [
                -1,
                -1,
                2
            ],
            [
                3,
                3,
                3
            ],
            [
                3,
                3,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                2,
                2,
                3
            ],
            [
                -1,
                -1,
                1
            ],
            [
                2,
                2,
                3
            ],
            [
                2,
                2,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                2
            ],
            [
                3,
                4,
                4
            ],
            [
                -1,
                -1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                2
            ],
            [
                -1,
                -1,
                3
            ],
            [
                2,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                5
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                3,
                4,
                6
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                2
            ],
            [
                3,
                4,
                4
            ],
            [
                2,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                1
            ],
            [
                3,
                3,
                3
            ],
            [
                2,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                1
            ],
            [
                4,
                4,
                4
            ],
            [
                -1,
                -1,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                -1,
                -1,
                3
            ],
            [
                1,
                4,
                4
            ],
            [
                3,
                3,
                3
            ],
            [
                -1,
                -1,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                1,
                5,
                5
            ],
            [
                4,
                4,
                4
            ],
            [
                -1,
                -1,
                -1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                4,
                5,
                5
            ],
            [
                4,
                5,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                4
            ],
            [
                -1,
                -1,
                1
            ],
            [
                4,
                4,
                4
            ],
            [
                3,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                3
            ],
            [
                1,
                4,
                4
            ],
            [
                3,
                3,
                3
            ],
            [
                2,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                2
            ],
            [
                -1,
                -1,
                2
            ],
            [
                1,
                3,
                3
            ],
            [
                2,
                2,
                3
            ],
            [
                2,
                2,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                3,
                4,
                4
            ],
            [
                3,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                3,
                3,
                4
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                3,
                3,
                4
            ],
            [
                3,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                3,
                6
            ],
            [
                -1,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                3,
                5
            ],
            [
                3,
                4,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                2,
                4
            ],
            [
                3,
                3,
                5
            ],
            [
                3,
                3,
                5
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                4,
                4
            ],
            [
                -1,
                4,
                5
            ],
            [
                -1,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                3,
                4
            ],
            [
                -1,
                3,
                5
            ],
            [
                4,
                4,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                2,
                4,
                4
            ],
            [
                3,
                3,
                4
            ],
            [
                3,
                3,
                4
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                -1
            ],
            [
                2,
                2,
                3
            ],
            [
                1,
                3,
                3
            ],
            [
                2,
                2,
                3
            ],
            [
                2,
                2,
                3
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                -1,
                -1,
                1
            ],
            [
                1,
                2,
                2
            ],
            [
                1,
                2,
                2
            ],
            [
                1,
                2,
                2
            ],
            [
                1,
                2,
                2
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                -1,
                -1,
                -1
            ],
            [
                1,
                1,
                1
            ],
            [
                1,
                1,
                1
            ],
            [
                1,
                1,
                1
            ],
            [
                1,
                1,
                1
            ],
            [
                1,
                1,
                1
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    },
    {
        "parsed_game_state": [
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ],
            [
                0,
                0,
                0
            ]
        ],
        "parsed_token_moved": [
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ],
            [
                false,
                false,
                false
            ]
        ]
    }
];
